version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
      target: db
    container_name: db
    ports:
      - 3306:3306
    restart: always
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: backend
    depends_on:
      - db
    ports:
      - 8080:8080
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 8085:80
