apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    app: db
spec:
  containers:
    - image: cloudapp_db
      name: db-container
      imagePullPolicy: Never
      ports:
        - containerPort: 3306
          name: http
          protocol: TCP
      livenessProbe:
        tcpSocket:
          port: 3306
        initialDelaySeconds: 120
        periodSeconds: 20
        failureThreshold: 3
