apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-persistent-volume
spec:
  storageClassName: db-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/persistent-volume"
